import { EmotionDefinition } from "@/types/emotion";

export const CONTROLLED_EMOTIONS: EmotionDefinition[] = [
  {
    id: "anxious",
    name: "Anxious",
    category: "challenging",
    iconName: "water_drop",
    description: "Worry about future outcomes, feeling ungrounded or restless",
    pebbleShapeClass: "pebble-shape-1",
    accentColorClass: "text-secondary",
    associatedConcepts: ["unattachment to results", "duty over outcome", "equanimity", "samatvam", "temporary nature of sensations"],
    associatedThemes: ["anxiety", "fear of future", "uncertainty", "worry", "stress", "control"],
    synonyms: ["anxious", "worried", "nervous", "apprehensive", "jittery", "dread", "uneasy", "panicky", "stressed"],
  },
  {
    id: "overwhelmed",
    name: "Overwhelmed",
    category: "challenging",
    iconName: "cyclone",
    description: "Too many demands, mental exhaustion, feeling consumed by tasks",
    pebbleShapeClass: "pebble-shape-2",
    accentColorClass: "text-on-surface-variant",
    associatedConcepts: ["focus of intellect (vyavasayatmika buddhi)", "surrender of burden", "mind mastery", "action without frantic agitation"],
    associatedThemes: ["burnout", "mental fatigue", "overload", "exhaustion", "pressure", "too much"],
    synonyms: ["overwhelmed", "exhausted", "drowning", "burned out", "burnt out", "swamped", "stretched thin", "breaking point"],
  },
  {
    id: "confused",
    name: "Confused",
    category: "contemplative",
    iconName: "route",
    description: "Unclear about direction, moral dilemma, divided mind",
    pebbleShapeClass: "pebble-shape-3",
    accentColorClass: "text-outline",
    associatedConcepts: ["discriminative intellect (viveka)", "inner clarity", "clarity of dharma", "resolving inner conflict"],
    associatedThemes: ["dilemma", "doubt", "indecision", "uncertainty", "identity", "direction"],
    synonyms: ["confused", "lost", "doubtful", "torn", "undecided", "conflicted", "uncertain", "perplexed", "hesitant"],
  },
  {
    id: "heavy",
    name: "Heavy",
    category: "challenging",
    iconName: "cloud",
    description: "Carrying deep sorrow, apathy, feeling burdened by past actions",
    pebbleShapeClass: "pebble-shape-4",
    accentColorClass: "text-muted-stone",
    associatedConcepts: ["transience of suffering", "witness consciousness (sakshi)", "endurance (titiksha)", "self-upliftment"],
    associatedThemes: ["grief", "sadness", "weight", "burdens", "sorrow", "regret", "inertia"],
    synonyms: ["heavy", "sad", "sorrowful", "down", "depressed", "melancholy", "burdened", "weighed down", "gloomy"],
  },
  {
    id: "hopeful",
    name: "Hopeful",
    category: "positive",
    iconName: "wb_sunny",
    description: "Sensing light ahead, seeking alignment, feeling faith rekindled",
    pebbleShapeClass: "pebble-shape-5",
    accentColorClass: "text-primary",
    associatedConcepts: ["faith (shraddha)", "divine grace", "perseverance in yoga", "spiritual optimism"],
    associatedThemes: ["hope", "optimism", "aspiration", "light", "faith", "renewal"],
    synonyms: ["hopeful", "optimistic", "inspired", "encouraged", "renewed", "faithful", "aspiring"],
  },
  {
    id: "seeking",
    name: "Seeking",
    category: "seeking",
    iconName: "self_improvement",
    description: "Desiring deeper purpose, wisdom, or self-realization",
    pebbleShapeClass: "pebble-shape-6",
    accentColorClass: "text-secondary",
    associatedConcepts: ["self-knowledge (atmagyana)", "liberation (moksha)", "devotion (bhakti)", "inquiry into the Self"],
    associatedThemes: ["purpose", "meaning", "wisdom", "spiritual path", "truth", "discovery"],
    synonyms: ["seeking", "searching", "yearning", "curious", "questing", "exploring", "inquiring", "looking for meaning"],
  },
  {
    id: "angry",
    name: "Angry",
    category: "challenging",
    iconName: "local_fire_department",
    description: "Frustration, indignation, resentment from unmet expectations",
    pebbleShapeClass: "pebble-shape-1",
    accentColorClass: "text-error",
    associatedConcepts: ["chain of desire and anger (krodhat bhavati sammohah)", "sense restraint", "calm wisdom", "forgiveness (kshama)"],
    associatedThemes: ["anger", "frustration", "rage", "irritation", "resentment", "bitterness"],
    synonyms: ["angry", "furious", "mad", "irritated", "enraged", "indignant", "resentful", "bitter", "pissed", "agitated"],
  },
  {
    id: "jealous",
    name: "Jealous",
    category: "challenging",
    iconName: "compare_arrows",
    description: "Comparison with others, fear of falling behind, envy",
    pebbleShapeClass: "pebble-shape-2",
    accentColorClass: "text-muted-stone",
    associatedConcepts: ["svadharma (one's own path)", "contentment (santosha)", "seeing the divine in all beings", "freedom from envy (anasuya)"],
    associatedThemes: ["comparison", "envy", "jealousy", "inferiority", "competition", "inadequacy"],
    synonyms: ["jealous", "envious", "comparing", "insecure", "covetous", "inferior", "left behind"],
  },
  {
    id: "grieving",
    name: "Grieving",
    category: "challenging",
    iconName: "heart_broken",
    description: "Processing profound loss, heartbreak, or life transitions",
    pebbleShapeClass: "pebble-shape-3",
    accentColorClass: "text-muted-stone",
    associatedConcepts: ["immortality of the soul (atman)", "impermanence of physical form", "compassionate detachment", "healing time"],
    associatedThemes: ["loss", "bereavement", "death", "heartbreak", "mourning", "letting go"],
    synonyms: ["grieving", "heartbroken", "mourning", "bereaved", "devastated", "broken", "aching"],
  },
  {
    id: "lonely",
    name: "Lonely",
    category: "challenging",
    iconName: "person",
    description: "Feeling isolated, unseen, or disconnected from community",
    pebbleShapeClass: "pebble-shape-4",
    accentColorClass: "text-outline",
    associatedConcepts: ["indwelling presence (Ishvara in the heart)", "universal interconnectedness", "friend of the self", "solitude as sanctuary"],
    associatedThemes: ["isolation", "loneliness", "alienation", "disconnection", "unseen", "solitude"],
    synonyms: ["lonely", "isolated", "alone", "unseen", "disconnected", "alienated", "abandoned", "solitary"],
  },
  {
    id: "restless",
    name: "Restless",
    category: "challenging",
    iconName: "air",
    description: "Mind jumping between thoughts, inability to sit in stillness",
    pebbleShapeClass: "pebble-shape-5",
    accentColorClass: "text-on-surface-variant",
    associatedConcepts: ["stillness of mind (chitta vritti nirodha)", "steady practice (abhyasa)", "dispassion (vairagya)", "calm breathing"],
    associatedThemes: ["restlessness", "racing mind", "distraction", "agitation", "hyperactive thoughts", "lack of focus"],
    synonyms: ["restless", "fidgety", "racing thoughts", "distracted", "scattered", "unfocused", "hyper", "turbulent mind"],
  },
  {
    id: "fearful",
    name: "Fearful",
    category: "challenging",
    iconName: "shield",
    description: "Threatened by vulnerability, fear of failure or the unknown",
    pebbleShapeClass: "pebble-shape-6",
    accentColorClass: "text-secondary",
    associatedConcepts: ["fearlessness (abhayam)", "refuge in the Self", "transcendence of death and fear", "courage in dharma"],
    associatedThemes: ["fear", "terror", "vulnerability", "dread", "insecurity", "intimidation", "fear of failure"],
    synonyms: ["fearful", "scared", "afraid", "terrified", "frightened", "panicked", "intimidated", "vulnerable"],
  },
];

export function getEmotionById(id: string): EmotionDefinition | undefined {
  const normalized = id.trim().toLowerCase();
  return CONTROLLED_EMOTIONS.find((e) => e.id === normalized);
}
