import { Shield, Award, BookOpen, Sparkles, HeartHandshake, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { CRISIS_RESOURCES } from "@/lib/safety/crisis-resources";

export default function AboutPage() {
  return (
    <div className="flex-1 max-w-3xl mx-auto w-full px-6 pt-24 pb-32 flex flex-col gap-10 animate-slide-up">
      {/* Header */}
      <div className="flex flex-col gap-4">
        <Link
          href="/"
          className="flex items-center gap-1.5 text-xs uppercase font-bold tracking-widest font-sans text-muted-stone hover:text-primary transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Reflect
        </Link>
        <div className="flex items-center gap-4 mt-2">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/logo.png"
            alt="Drishti Logo"
            className="w-16 h-16 md:w-20 md:h-20 rounded-full object-cover border-2 border-gold/40 shadow-soft shrink-0"
          />
          <div>
            <h1 className="font-serif text-3xl md:text-5xl font-bold text-primary">About Drishti</h1>
            <p className="font-sans text-base md:text-lg text-muted-stone leading-relaxed mt-1">
              A modern philosophical reflection companion rooted in the timeless equanimity of the Bhagavad Gita.
            </p>
          </div>
        </div>
      </div>

      {/* 4-Layer Trust Model Section */}
      <section className="bg-surface-container/90 rounded-3xl p-6 md:p-8 border border-gold/30 shadow-soft flex flex-col gap-6">
        <div className="flex items-center gap-3">
          <span className="w-10 h-10 rounded-full bg-parchment-deep flex items-center justify-center text-gold-muted">
            <Shield className="w-5 h-5" />
          </span>
          <div>
            <h2 className="font-serif font-bold text-xl md:text-2xl text-primary">The 4-Layer Trust Model</h2>
            <p className="text-xs text-muted-stone font-sans">Transparent separation of original text vs. AI synthesis</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-2xl bg-white/80 border border-outline-variant/30 flex flex-col gap-2">
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-amber-100/80 text-amber-900 w-fit">
              <Award className="w-3 h-3 text-amber-700" /> Layer 1: Sanskrit Source
            </span>
            <p className="text-xs text-on-surface leading-relaxed font-sans">
              Immutable original verses in Devanagari Sanskrit from the canonical 701-verse Bhagavad Gita corpus.
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-white/80 border border-outline-variant/30 flex flex-col gap-2">
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-stone-100 text-stone-900 w-fit">
              <BookOpen className="w-3 h-3 text-stone-600" /> Layer 2: Canonical Translation
            </span>
            <p className="text-xs text-on-surface leading-relaxed font-sans">
              Direct word meanings and translations verified against classical lineage concordances (Swami Sivananda & classical acharyas).
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-white/80 border border-outline-variant/30 flex flex-col gap-2">
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-emerald-100/80 text-emerald-900 w-fit">
              <Shield className="w-3 h-3 text-emerald-700" /> Layer 3: Traditional Commentary
            </span>
            <p className="text-xs text-on-surface leading-relaxed font-sans">
              Historical commentary from classical commentaries, presented strictly when scholarly sources are available.
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-white/80 border border-outline-variant/30 flex flex-col gap-2">
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-indigo-50 text-indigo-900 w-fit">
              <Sparkles className="w-3 h-3 text-indigo-600" /> Layer 4: AI Synthesis
            </span>
            <p className="text-xs text-on-surface leading-relaxed font-sans">
              Empathetic reflection, practical contextual application, and contemplative inquiry generated by AI — clearly labeled as non-authoritative.
            </p>
          </div>
        </div>
      </section>

      {/* Safety & Crisis Disclaimer Section */}
      <section className="bg-amber-50/80 rounded-3xl p-6 md:p-8 border border-amber-200 shadow-soft flex flex-col gap-4">
        <div className="flex items-center gap-3">
          <span className="w-10 h-10 rounded-full bg-amber-200/70 text-amber-900 flex items-center justify-center">
            <HeartHandshake className="w-5 h-5" />
          </span>
          <h2 className="font-serif font-bold text-xl text-amber-950">Safety & Crisis Commitment</h2>
        </div>

        <p className="text-sm text-amber-900 font-sans leading-relaxed">
          Drishti is a philosophical companion and reflective diary. It is <strong>not a medical, mental health, or crisis service</strong>. Our safety-first pipeline automatically detects signs of acute crisis or self-harm before RAG retrieval, immediately pausing philosophical advice to provide verified emergency helpline resources.
        </p>

        <div className="pt-2">
          <h4 className="text-xs font-bold uppercase tracking-wider text-amber-950 mb-2">Configured Helplines:</h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs font-sans text-amber-900">
            {CRISIS_RESOURCES.map((r, idx) => (
              <div key={idx} className="bg-white/70 p-2.5 rounded-lg border border-amber-100">
                <span className="font-semibold">{r.resourceName}</span>: {r.phone || r.website}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Corpus & Ingestion Provenance */}
      <section className="flex flex-col gap-3">
        <h3 className="font-serif font-bold text-lg text-primary">Corpus Provenance</h3>
        <p className="font-sans text-sm text-muted-stone leading-relaxed">
          The initial corpus contains 701 Bhagavad Gita verses across all 18 chapters with Sanskrit Devanagari text, Romanized IAST transliteration, and English translations. Semantic retrieval is powered by vector embeddings and deterministic multi-factor reranking.
        </p>
      </section>
    </div>
  );
}
